# Metadata about this component, to be used in the CMS
spec:
  structures:
    - ""
  label: Portfolio item
  description: Image and details
  icon: 
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  category: ""
  image: ""
  image_alt: ""
  date: ""
  title: ""
  subtitle: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  category: category-1
  image: /images/portfolio/portfolio-img1.jpg
  image_alt: Portfolio
  date: '16.03.2015'
  title: Merit wogmonk
  subtitle: Branding

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
