# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: Map
  description: Map with location pin
  icon: call
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  latitude: ""
  longitude: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  latitude: "51.507351"
  longitude: "-0.127758"

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
