# Metadata about this component, to be used in the CMS
spec:
  structures:
    - ""
  label: Single testimonial
  description: Single testimonial
  icon: rate_review
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content: ""
  author_image: ""
  author_image_alt: ""
  author_name: ""
  author_career: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  content: Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam
    nonummy nibh euismod tincidunt ut laoreet dolore magna. ipsum dolor sit
    amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt
    ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam.
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo vitae natus
    odio quasi recusandae, esse! Libero ipsum cum aliquid, nisi, maiores animi
    iste vel consectetur error facilis quae ducimus sint beatae vitae nesciunt
    explicabo esse nam. Soluta harum ipsa officia nam adipisci velit debitis!
    Dolore a ducimus, assumenda aspernatur fugit!
  author_image: /images/clients-img1.png
  author_image_alt: Clients
  author_name: Paul Lapkin
  author_designation: CEO at DeviserWeb

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
