collections_config:
  pages:
    _enabled_editors:
      - visual
  portfolios:
    schemas:
      default:
        path: schemas/portfolio.md
  posts:
    schemas:
      default:
        path: schemas/post.md
data_config: true