# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Testimonials Block
  description: Testimonials with heading
  icon: rate_review
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  background_image: ""
  heading: bookshop:generic/heading
  testimonials: [bookshop:simple/testimonial]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  background_image: /images/slider/bg-3.jpg
  heading: bookshop:generic/heading
  testimonials:
    - bookshop:simple/testimonial
    - bookshop:simple/testimonial

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
