# Metadata about this component, to be used in the CMS
[spec]
structures = ['content_blocks']
label = 'Client logos'
description = 'Client logos'
icon = 'people_outline'
tags = []

# Defines the structure of this component, as well as the default values
[blueprint]
background_image = ''
[[blueprint.client_logos]]
image_src = ''
image_alt = ''

# Overrides any fields in the blueprint when viewing this component in the component browser
[preview]
background_image = 'images/slider/bg-1.jpg'
[[preview.client_logos]]
image_src = 'images/clients-logo/client-logo-1.png'
image_alt = 'Client Logo'
[[preview.client_logos]]
image_src = 'images/clients-logo/client-logo-1.png'
image_alt = 'Client Logo'

# Any extra CloudCannon inputs configuration to apply to the blueprint
[_inputs]