# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Client logos
  description: Client logos
  icon: people_outline
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  background_image: ""
  client_logos: [bookshop:generic/client-logo]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  background_image: /images/slider/bg-1.jpg
  client_logos:
    - bookshop:generic/client-logo
    - bookshop:generic/client-logo

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
