# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
    - hero_blocks
  label: Hero
  description: Small hero for single page layouts
  icon: title
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: ""
  subheading: ""
  image: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  heading: Our Services.
  subheading: We ensure Quality Design.
  image: /images/header/services-folding-img.jpg
   
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}