# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Slider hero
  description: Hero header with sliding images/text
  icon: title
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  slider_items: [bookshop:simple/slider-item]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  slider_items: 
   - bookshop:simple/slider-item
   - bookshop:simple/slider-item
   
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
