# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Services
  description: Grid of icons with content
  icon: 
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  slider_items: [bookshop:simple/slider-item]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  service: 
   - bookshop:simple/slider-item
   - bookshop:simple/slider-item
   
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
