# Metadata about this component, to be used in the CMS
spec:
  structures:
    - ""
  label: Heading
  description: Generic heading
  icon: title
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  heading: Case Study

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
