# Metadata about this component, to be used in the CMS
spec:
  structures:
    - ""
  label: Pricing plan
  description: A single plan and its features
  icon: 
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
    heading: ''
    price: ''
    plan_length: ''
    features: [bookshop:simple/plan-feature]
    link: bookshop:generic/link

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
    heading: extended Version
    price: '89.00'
    plan_length: Month
    features:
      - bookshop:simple/plan-feature
      - bookshop:simple/plan-feature
      - bookshop:simple/plan-feature
    link: bookshop:generic/link
   
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}