# Metadata about this component, to be used in the CMS
spec:
  structures:
    - ""
  label: Icon and content
  description: Content with supporting icon
  icon: image
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  icon: "tf-presentation"
  heading: ""
  content: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  heading: Mobile App UI
  content: We provide various  mobile app UI Design services Android, ios,windows phone. As well as we follow latest trend in our molestie consequat.
   
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  icon:
    type: select
    options:
      values:
        - tf-mobile
        - tf-telescope
        - tf-presentation
        - tf-strategy
        - tf-anchor2
        - tf-globe
        - tf-desktop
        - tf-laptop
        - tf-book-open
        - tf-picture
        - tf-printer
        - tf-wallet
        - tf-attachment
        - tf-tools
        - tf-chat
        - tf-dial
        - tf-global