# Metadata about this component, to be used in the CMS
spec:
  structures:
    - ""
  label: link
  description: link
  icon: smart_button
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  url: ""
  content: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  url: "#"
  content: View More

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
