# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Map and Details
  description: Company details with a map showing company location
  icon: map
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
    business_card: bookshop:simple/business-card
    map: bookshop:generic/map

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
    business_card: bookshop:simple/business-card
    map: bookshop:generic/map
   
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}