# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Team member
  description: Staff picture and details
  icon: crop_original
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  image: ""
  image_alt: ""
  name: ""
  job_title: ""
  description: ""
  facebook_url: ""
  twitter_url: ""
  linkedin_url: ""
  google_url: ""
  instagram_url: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  image: /images/team/team-pic1.jpg
  image_alt: Team img
  name: aurelien salomo
  job_title: Creative Director
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam
    ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim.
  facebook_url: "#"
  twitter_url: "#"
  linkedin_url: "#"
  google_url: "#"
  instagram_url: "#"

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
