# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Filter buttons
  description: Filtering buttons for portfolio items with heading
  icon: 
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: bookshop:generic/heading
  buttons: [bookshop:generic/filter-button]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  heading: bookshop:generic/heading
  buttons:
    - bookshop:generic/filter-button
    - bookshop:generic/filter-button
    - bookshop:generic/filter-button
    
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
