# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Case study
  description: Title and left right blocks
  icon: vertical_split
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  background: grey
  heading: bookshop:generic/heading
  left_right_blocks: [bookshop:simple/left-right-block]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  heading: bookshop:generic/heading
  left_right_blocks: 
   - bookshop:simple/left-right-block
   
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  background:
    type: select
    options:
      values:
        - grey
        - black
