# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Staff block
  description: Staff pictures and information
  icon: collections
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: bookshop:generic/heading
  team_members: [bookshop:generic/team-member]
  link: bookshop:generic/link

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  heading: bookshop:generic/heading
  team_members:
    - bookshop:generic/team-member
    - bookshop:generic/team-member
    - bookshop:generic/team-member
  link: bookshop:generic/link
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
