# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Pricing table
  description: A table of different pricing plans available
  icon: view_column
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
    heading: bookshop:generic/heading
    pricing_plans: [bookshop:simple/pricing-plan]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
    heading: bookshop:generic/heading
    pricing_plans:
      - bookshop:simple/pricing-plan
      - bookshop:simple/pricing-plan
      - bookshop:simple/pricing-plan
   
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}