# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Contact form
  description: Form to submit contact details and a message
  icon: contact_mail
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: bookshop:generic/heading
  button_content: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  heading: bookshop:generic/heading
  button_content: "Send message"
   
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}