# Metadata about this component, to be used in the CMS
spec:
  structures:
    - ""
  label: Client Logo
  description: Client logo
  icon: person_outline
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  image: ""
  image_alt: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  image: /images/clients-logo/client-logo-1.png
  image_alt: Client Logo

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
