# Metadata about this component, to be used in the CMS
spec:
  structures:
    - ""
  label: Left right block
  description: Content and image in two columns
  icon: vertical_split
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  image_alignment: right
  background: grey
  heading: ""
  content_html: ""
  link: bookshop:generic/link
  image: ""
  image_alt: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  heading: E Banks That Accept Us Casino Players
  content_html: Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam
    nonummy nibh euiyd tincidunt ut laoreet dolore magna aliquam nibh
    utpat.Ullamcorper suscipit lobo nibh euiyd tinci- dunt ut laoreet.</br>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem impedit
    molestias cumque dolorum, sunt, provident blanditiis tempora, aut explicabo
    error ipsa repudiandae. Dolores eius eaque eum mollitia esse nisi
    necessitatibus distinctio ea, dolorem non, optio minima temporibus
    blanditiis, quidem aperiam!</p>
  image: /images/case-study/case-study-img1.png

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  image_alignment:
    type: select
    options:
      values:
        - right
        - left
  background:
    type: select
    options:
      values:
        - grey
        - black
