# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Video hero
  description: Hero header with video in background
  icon: title
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: ""
  subheading: ""
  background_video: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  heading: We’re Creative
  subheading: We Ensure Quality Design
  background_video: /video/ocean

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  background_video:
    type: file

