# Metadata about this component, to be used in the CMS
spec:
  structures:
    - ""
  label: Gallery Image
  description: Single image link
  icon: add_photo_alternate
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  image: ""
  image_alt: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  image: /images/portfolio/single-portfolio-img2.jpg

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}