# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Services
  description: Grid of icons with content
  icon: view_module
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: bookshop:generic/heading
  service: [bookshop:simple/icon-and-content]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  service: 
   - bookshop:simple/icon-and-content
   - bookshop:simple/icon-and-content
   - bookshop:simple/icon-and-content
   - bookshop:simple/icon-and-content
   - bookshop:simple/icon-and-content
   - bookshop:simple/icon-and-content
   
# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
